### ISSUE TITLE
Can you describe the difference between the various ksw_*

### ISSUE THREAD

**Issue by nh13** [attractivechaos/klib#101]
@attractivechaos @lh3 

I am trying to figure out the types of alignment based on the function names, guessing the following:

* `ksw_align` - local alignment: a sub-sequence of the query aligned to a sub-sequence of the target
* `ksw_extend` - a prefix of the query aligned to a prefix of the target**
* `ksw_global` - alignment of the full query to the full target

`**` doesn't behave this way, which is why I am asking

Also, I have a `ksw_glocal` implementation if you are looking for a contribution.

**Comment by attractivechaos** [comment]
Extension is also called seed extension. You have to have a seed hit before calling it, or it won't give you meaningful result. Also, don't use ksw. Use ksw2.

**Comment by nh13** [comment]
I see, you don't feed the sequence _after_ the seed, you feed in the sequence with the seed included.

`ksw2` doesn't have local or `glocal`.  It was much easier to use `ksw_local`, and adapt `ksw_global` to create `ksw_glocal`.

**Comment by lh3** [comment]
Local alignment is ok. `ksw_global` is buggy and I have no plan to fix it. Don't use.

**Comment by lh3** [comment]
Forgot to say – ksw2 has a global alignment implementation, which is more correct.

**Comment by nh13** [comment]
Thanks Heng, this is great information.  I will be porting over the global, extension, and glocal (an overloaded term) to use ksw2.  The latter is the full query to a sub-sequence of the target, so I think I can just use global and trim off the start/end deletions.  

I'll keep relying on klib's `ksw_local` until such time that `ksw2` has a local implementation.  

Thanks for the quick responses and helpful insights as always.
