### ISSUE TITLE
is khash thread-safe when used read-only?

### ISSUE THREAD

**Issue by kullanici0606** [attractivechaos/klib#109]
Hi,

I want to populate a hash set in the beginning of program and want to do lookups from several threads. Hash set will be read-only. Is khash thread-safe for this type of situation (i.e concurrent readers)? I looked documentation but couldn't find anything about it.

**Comment by attractivechaos** [comment]
Yes, reading is thread safe. Writing is not.

**Comment by kullanici0606** [comment]
Thanks a lot for the information
