### ISSUE TITLE
description for KHASH_SET_INIT_INT64(name) incorrectly says it instantiates a map

### ISSUE THREAD

**Issue by bkerin** [attractivechaos/klib#112]
Currently it looks like this:

/*! @function
  @abstract     Instantiate a hash map containing 64-bit integer keys
  @param  name  Name of the hash table [symbol]
 */
#define KHASH_SET_INIT_INT64(name)                                                                              \
        KHASH_INIT(name, khint64_t, char, 0, kh_int64_hash_func, kh_int64_hash_equal)

@abstract should read: "Instantiate a hash set containing 64 bit integer keys"

**Comment by attractivechaos** [comment]
Fixed.
