### ISSUE TITLE
khint64_t is a misleading name for an unsigned value

### ISSUE THREAD

**Issue by bkerin** [attractivechaos/klib#113]
khuint64_t would be a lot better for consistency with everything in stdint.h
same for khint32_t

**Comment by attractivechaos** [comment]
stdint.h is a C99 header. Not every compiler supports C99.

**Comment by bkerin** [comment]
But being consistent with this (good) C99 naming scheme is zero-cost even on non-C99 compilers.  Granted it would be better if int was unsigned by default and 'signed int' meant signed but that can't be changed :)

**Comment by lh3** [comment]
> But being consistent with this (good) C99 naming scheme is zero-cost even on non-C99 compilers. 

No way. Older compilers won't work if you include stdint.h.

**Comment by bkerin** [comment]
No, what I mean is it would be nice if the khash int type names were khuint32_t and khuint64_t, like so:

#if UINT_MAX == 0xffffffffu
typedef unsigned int khuint32_t;
#elif ULONG_MAX == 0xffffffffu
typedef unsigned long khuint32_t;
#endif

#if ULONG_MAX == ULLONG_MAX
typedef unsigned long khuint64_t;
#else
typedef unsigned long long khuint64_t;
#endif

stdint.h types are very familiar to many now and it's jarring and even confusing on first sight to see type names not use the convention.

**Comment by attractivechaos** [comment]
I see. That makes sense. However, what's done is done. Changing now would break compatibility. This will stay.
