### ISSUE TITLE
kvec: remove need to pass type?

### ISSUE THREAD

**Issue by damag** [attractivechaos/klib#117]
Many of kvec.h function macros require passing the type being stored (kv_resize, kv_copy, kv_push, kv_pushp, kv_a) but this seems to not actually be needed. It's only used for two reasons:

* To cast the pointer returned from realloc(), which is not actually needed in C where the preferred style is usually to not cast from a void pointer when assigning to a variable.
* In sizeof(type) which could be changed to sizeof(*(v).a)

Has this not been changed simply to not break the current API?

**Comment by attractivechaos** [comment]
Then kvec won't work with C++. All klib components are supposed to be compiled with a C++ compiler. We may use `__typepf__`, but that is a compiler extension.

**Comment by bfredl** [comment]
@damag FWIW neovim's fork of this library https://github.com/neovim/neovim/blob/master/src/nvim/lib/kvec.h has some of these changes.

**Comment by damag** [comment]
Ah nice, thanks for the info.
