### ISSUE TITLE
Can kdq_shift be called without locking thread?

### ISSUE THREAD

**Issue by 7PintsOfCherryGarcia** [attractivechaos/klib#142]
My working threads get data from kdq until a NULL pointer is obtained. 

Is calling kdq_shift on the same queue across multiple threads safe? Or would it be advisable to lock beforehand?

**Comment by attractivechaos** [comment]
kdq_shift is not thread safe, unfortunately. You have to lock this call.

**Comment by 7PintsOfCherryGarcia** [comment]
Perfect, thanks!!
