### ISSUE TITLE
Hash signs in column converted into 'hash' on plot when using corr_plot

### ISSUE THREAD

**Issue by ogola89** [attractivechaos/klib#150]
Hi there,

Thanks for this great library.

When I used the corr_plot() function, I am plotting columns such as "lymphocyte# 10^3/mm3", but these get turned into "lymphocyte_hash_10^3_mm3" on the plot, which means it is not ideal for sharing, as it's not always obvious that the word hash means number unlike the symbol.

Any idea why this is, whether it can be changed and how to get around it (without changing the # to 'num' for example)?

**Comment by attractivechaos** [comment]
Unrelated to this repo.
