### ISSUE TITLE
strange kb_generic_cmp function

### ISSUE THREAD

**Issue by UnixJunkie** [attractivechaos/klib#61]
Hello,
In kbtree.h why
#define kb_generic_cmp(a, b) (((b) < (a)) - ((a) < (b)))
is not simply
#define kb_generic_cmp(a, b) ((a) - (b))

**Comment by lh3** [comment]
To avoid number under/over-flow

**Comment by lh3** [comment]
Also, `a` and `b` could be `unsigned`. Then `a-b` is always non-negative.

**Comment by UnixJunkie** [comment]
OK, thanks!
