### ISSUE TITLE
 infinite loop in kseq_read for  gz files that fail crc check

### ISSUE THREAD

**Issue by pmelsted** [attractivechaos/klib#78]
When a gz file fails the crc check kseq_read enters an infinite loop.

This happens in https://github.com/attractivechaos/klib/blob/master/kseq.h#L101

The __read method when using gzread returns -1 when the crc check fails and the for loop never exits.

I have reproduced this bug using the test program from [your website](http://attractivechaos.github.io/klib/#Kseq%3A%20stream%20buffer%20and%20FASTA%2FQ%20parser) and the two supplied files. They are identical except I messed with a  CRC byte in t.fastq.gz

[reads_2.fastq.gz](https://github.com/attractivechaos/klib/files/704357/reads_2.fastq.gz)
[t.fastq.gz](https://github.com/attractivechaos/klib/files/704358/t.fastq.gz)

Interestingly seqtk does not fail, although it doesn't read all the lines
```
> seqtk seq t.fastq.gz | wc -l
   39842
> seqtk seq reads_2.fastq.gz| wc -l
   40000
```

and gzcat (mac version of zcat) notices the error, but it returns the original data.
```
> gzcat reads_2.fastq.gz > /dev/null
> gzcat t.fastq.gz>  /dev/null
gzcat: invalid compressed data--crc error
gzcat: t.fastq.gz: uncompress failed
```

**Comment by pmelsted** [comment]
Another question is what is the correct behaviour of kseq in cases where `__read` returns a `-1`. Should it return a `-1: end-of-file` or another error code, say `-3: file-error`?

**Comment by lh3** [comment]
Yes, return value from read/gzread should be checked. Could you send a pull request? Thanks a lot for this!
