### ISSUE TITLE
Need to check how much memory my hash table has taken after inserting 1 million key values

### ISSUE THREAD

**Issue by vikash009** [attractivechaos/klib#88]
Here is the code.

https://github.com/attractivechaos/klib/blob/master/khash.h

What I want: I am entering n unique entry in this table. and after inserting key and value i want to check how much space this hastable is consuming.

Issue: Example after entering 1000 entry. When i try to get the size of hastable using kh_size(h) function given in "khash.h" I am getting 387 entry only. But when i am trying get the value by giving the key I am able to get.

Here is my code:  PFA.
`#include <stdio.h>
#include <stdlib.h>
#include "khash.h"
#include "string.h"

#define kh_get_val(kname, hash, key, defVal) ({k=kh_get(kname, hash, key);(k!=kh_end(hash)?kh_val(hash,k):defVal);})
#define kh_set(kname, hash, key, val) ({int ret; k = kh_put(kname, hash,key,&ret); kh_value(hash,k) = val; ret;})

const int khIntInt = 33;

KHASH_MAP_INIT_INT(khIntInt, long long) // setup khash to handle string key with int payload
//KHASH_MAP_INIT_STR(khStrInt, long long) // setup khash to handle string key with int payload
       int int_key_int_body_example(char * filename)
      {
   	     printf("\n\nBegin khash test string key with int payload\n");
  	     int ret, is_missing;
   	     khiter_t k;
   	     char *tval;
	     khash_t(khIntInt) *h = kh_init(khIntInt); // create a hashtable
    	     printf("\n --------------------------------- FILE READ AND WRITE OPERTAION -------------------\n");
	
        FILE *fp;
    	int * ch;
    	char line[200];
    	fp=fopen(filename,"r");
    	if(!fp)
    	{
                perror("could not find the file");
                exit(0);
    	}

   	printf("\n ------------------------------------------------- PUTTING ALL KEYS ---------------------\n");

   	int count=0;
   	long long val_line=0;
        while (fgets ( line, 200, fp ) != NULL ) {
	
        printf(" Trying to Add key = %s and value = %s count =%lu \n", line,line,count++);
        val_line = strtoll(line, NULL, 0);
        printf("\n int_key_int_body: Here is the value in integer After Atoi = %ld \n",val_line);
        kh_set(khIntInt, h, val_line, val_line);
        printf(" ### DEBUG: h->n_buckets=%d,h->size=%d,h->n_occupied=%d,h->upper_bound=%d \n ",h->n_buckets,h->size,h->n_occupied,h->upper_bound);
        }
               fseek(fp, 0, SEEK_SET);
               printf("\n ------------------------------------------------- GETTING ALL VALUES ---------------------\n");
               count=0;
              while (fgets ( line, 200, fp ) != NULL ) {
                     val_line = strtoll(line, NULL, 0);
                     printf("\n int_key_int_body: Here is the value in integer After Atoi = %ld \n",val_line);
                     k=kh_get(khIntInt, h, val_line);
                    if (k == kh_end(h)) {
                         printf("no key found for line=%ld",val_line);
                    } else {
                        printf("GET value for  key = %s and value = %d count =%lu and k_iterator=%d \n", 
                        line,kh_val(h,k),count++,k);
                  }
               }
              printf("\n ------------------------------------------------- ---------------------\n");
              kh_destroy(khIntInt, h);
              return 0;
     }
       int main( int argc, char *argv[] ) 
      {
          char *filename;
          filename=argv[1];
          printf("\n filename=%s",filename);
          int_key_int_body_example(filename);
     }`

**Comment by attractivechaos** [comment]
Call `n=kh_n_buckets(hash_tab)`. The total memory is `n*(sizeof(key_type)+sizeof(value_type)+0.25)`.

**Comment by vikash009** [comment]
Thanks for reply. Here is some query.

1. n=kh_n_buckets(hash_tab ) =>> It gives number of bucket. right. 
so if  I am using 
KHASH_MAP_INIT_INT64(khIntInt, long long)

so total memory = n * (sizeof(long long)+sizeof(long long)+0.25) bytes  ==>> correct ??

2.  kh_size(h) : why it is giving less number of elements ?  In my case for for 1000 entry it is giving 387.
